import type { DungeonReportJson } from './dungeon-types.js';
import type {
  RenderCardItem,
  RenderDocument,
  RenderMetric,
  RenderPreset,
} from '../../render/render-document.js';

function truncate(value: string, maxLength: number) {
  if (value.length <= maxLength) {
    return value;
  }
  return `${value.slice(0, Math.max(0, maxLength - 1))}…`;
}

function formatDate(value: string | null | undefined) {
  if (!value) {
    return '—';
  }

  return value.slice(0, 10);
}

function metric(label: string, value: string | number, detail?: string): RenderMetric {
  return {
    label,
    value: String(value),
    detail,
  };
}

function reportBackgroundImage(report: DungeonReportJson) {
  return (
    report.dungeons.find((dungeon) => dungeon.records.latestClear?.activity.pgcrImageUrl)?.records
      .latestClear?.activity.pgcrImageUrl ??
    report.dungeons.find((dungeon) => dungeon.variants[0]?.pgcrImageUrl)?.variants[0]?.pgcrImageUrl ??
    null
  );
}

function dungeonCards(report: DungeonReportJson): RenderCardItem[] {
  return report.dungeons.map((dungeon) => ({
    title: truncate(dungeon.dungeon.name, 18),
    subtitle: `${dungeon.stats.attempts} attempts · ${dungeon.stats.failed} failed`,
    imageUrl:
      dungeon.records.latestClear?.activity.pgcrImageUrl ??
      dungeon.records.fastestFullClear?.activity.pgcrImageUrl ??
      dungeon.variants[0]?.pgcrImageUrl,
    badge: dungeon.stats.soloFlawlessClears > 0 ? `SF ${dungeon.stats.soloFlawlessClears}` : undefined,
    metrics: [
      metric('Clear', `${dungeon.stats.clears}/${dungeon.stats.attempts}`),
      metric('Full', dungeon.stats.fullClears),
      metric('Solo', dungeon.stats.soloClears),
    ],
  }));
}

export function dungeonReportToRenderDocument(
  report: DungeonReportJson,
  preset: RenderPreset,
): RenderDocument {
  const totals = report.totals;
  const pgcrLabel = `${report.completeness.pgcrLoaded}/${report.completeness.pgcrRequested}`;
  const sections: RenderDocument['sections'] = [
    {
      kind: 'card-grid',
      title: 'Dungeon Breakdown',
      cards: dungeonCards(report),
      columns: 2,
      cardWidth: 448,
      cardHeight: 188,
    },
  ];

  return {
    preset,
    kicker: 'Destiny 2 Dungeon',
    title: 'Dungeon Report',
    subtitle: `${report.account.displayName} · ${formatDate(report.generatedAt)} · ${report.completeness.historyActivities} activities`,
    backgroundImageUrl: reportBackgroundImage(report),
    metrics: [
      metric('Attempts', totals.attempts, `${totals.failed} failed`),
      metric('Clears', totals.clears),
      metric('Full', totals.fullClears),
      metric('Failed', totals.failed),
      metric('Solo', totals.soloClears),
      metric('Solo Flawless', totals.soloFlawlessClears),
      metric('PGCR', pgcrLabel),
    ],
    sections,
    footer: `Bungie API · ${report.completeness.partial ? 'Partial PGCR data' : 'Complete PGCR data'} · Generated by d2-skill`,
  };
}
